#server:
#  port: 8081
#  context-path: /learn-sb-karthik
#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/employee
#    username: root
#    password: 
server:
  port: 8081
  context-path: /learn-sb-karthik
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/sample
    username: root
    password: 
    
 